# Generated by Django 2.2.7 on 2019-12-17 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yamod', '0006_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='pictures',
            field=models.ManyToManyField(blank=True, to='yamod.Media'),
        ),
    ]
