# Generated by Django 2.2.7 on 2020-01-05 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField()),
                ('year_of_birth', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GameType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('points', models.PositiveIntegerField()),
                ('question', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('original_file_name', models.TextField()),
                ('content_type', models.TextField()),
                ('size', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tale',
            fields=[
                ('title', models.TextField()),
                ('type', models.CharField(choices=[('a', 'Action'), ('c', 'Comedy')], max_length=1, null=True)),
                ('text', models.TextField()),
                ('quiz', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='edutales.Quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='edutales.Destination')),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='edutales.Destination')),
                ('points', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='edutales.Quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('year_of_birth', models.IntegerField()),
                ('children', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='edutales.Child')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='edutales.Region')),
            ],
        ),
        migrations.AddField(
            model_name='destination',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='edutales.Quiz'),
        ),
        migrations.AddField(
            model_name='child',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='edutales.GameType'),
        ),
        migrations.AddField(
            model_name='child',
            name='progress',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='edutales.Progress'),
        ),
        migrations.AddField(
            model_name='child',
            name='reward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='edutales.Reward'),
        ),
        migrations.AddField(
            model_name='destination',
            name='tale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='edutales.Tale'),
        ),
    ]
