# Generated by Django 2.2.7 on 2020-01-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edutales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='pictures',
            field=models.ManyToManyField(blank=True, to='edutales.Media'),
        ),
    ]
