# Generated by Django 2.2.7 on 2020-01-15 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edutales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='game',
        ),
    ]
