# Generated by Django 2.2.7 on 2020-01-22 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edutales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='is_true',
            new_name='isTrue',
        ),
    ]
