# Generated by Django 2.2.7 on 2020-01-10 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('edutales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='last_name',
        ),
        migrations.AddField(
            model_name='parent',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
