# Generated by Django 2.2.7 on 2020-01-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edutales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='answer',
        ),
        migrations.AddField(
            model_name='quiz',
            name='answer',
            field=models.ManyToManyField(blank=True, to='edutales.Answer'),
        ),
    ]
