# Generated by Django 2.2.7 on 2020-01-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edutales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name': 'History', 'verbose_name_plural': 'Histories'},
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='answer',
        ),
        migrations.AddField(
            model_name='reward',
            name='pictures',
            field=models.ManyToManyField(blank=True, to='edutales.Media'),
        ),
    ]
