# Generated by Django 2.2.7 on 2020-01-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edutales', '0002_remove_child_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='game',
            field=models.CharField(choices=[('p', 'Pink'), ('b', 'Blue'), ('g', 'Green')], max_length=1, null=True),
        ),
    ]
