# Generated by Django 2.2.7 on 2020-01-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edutales', '0002_auto_20200120_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='children',
        ),
        migrations.AddField(
            model_name='parent',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='parent', to='edutales.Child'),
        ),
    ]
