# Generated by Django 2.2.7 on 2020-01-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edutales', '0002_auto_20200119_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='answer',
            field=models.TextField(null=True),
        ),
    ]
