# Generated by Django 2.2.7 on 2020-01-10 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edutales', '0003_auto_20200110_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='year_of_birth',
        ),
    ]
