# Generated by Django 2.2.7 on 2020-01-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edutales', '0004_remove_child_year_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='year_of_birth',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parent',
            name='year_of_birth',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
